# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='thumbs_up',
        ),
    ]
